IS-15829 Complete support for SalesOrderLines
sesam-io/powerofficego-connector pull request #47
Opened 2023-09-11 13:44 UTC by parhambarazesh

2023-09-11 14:00 UTC, ellis-igneri requested changes

2023-09-11 14:00 UTC, ellis-igneri commented on templates/system.json
I think you are deleting operations that other datatypes need

2023-09-11 14:29 UTC, parhambarazesh commented on templates/system.json
v1 operations are added

2023-09-12 06:46 UTC, ellis-igneri approved these changes

2023-09-12 06:54 UTC, merged